### ISSUE TITLE
Applying the deleted=True condition when joining a non soft delete model with a soft delete model

### ISSUE THREAD

**Issue by yanivps** [miguelgrinberg/sqlalchemy-soft-delete#13]
First of all thank you so much for the great blog and this great solution for applying soft delete in SQLAlchemy @miguelgrinberg !

I found that when I try to do `User.query.join(Message)`
It generates a query with a join statement and then apply the `'where users.deleted = true'` 😀

However, sometimes we perform the opposite which is `Message.join(User)` as we want to work with `Message` objects and in this case the `'where users.deleted = true'` is not included in the generated query by SQLAlchemy.
Can you please provide some guidelines on how this `'where users.deleted = true'` can be applied automatically even when performing a join between a non soft delete model --> a soft delete model.

P.S.
I've found that it is possible to do `Message.join(User.query)` which yields a join with anonymous query of users but I can't guarantee that developers will always remember to use User.query when they do join and eventually introduce a bug in the system

Thanks!

**Comment by miguelgrinberg** [comment]
To do this you need to create a custom query class in all the models that need this, and then override the appropriate method(s) to automatically insert the filtering. Basically the same thing that the User model does needs to be done in the Message query, with the difference that filtering messages from deleted users is a bit more tricky, since you have to do the join first.

**Comment by yanivps** [comment]
Thank you for you quick response
I've investigated a bit more this soft deletion in SQLAlchemy before going and monkey patching the entire thing and I've founded that in SQLAlchemy version 1.4 there is a mechanisim to hook all ORM queries and add a criteria quite simply. The advantage of their approach is that it also supports relationship loading, eager or lazy load. 
There even is an example in the docs here:
https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html

So hopefully this will be helpful for others seeking for this feature
Note: In version 1.4.33 there was a bug fixed regarding this so for anyone using this version all should be working quite well
